### PR TITLE
Fix : remaining length was not updated in code for the digits printed out in json 

### PR DESCRIPTION
**Pull request by jaymin1328**
'remLen' was not properly decreased. The number of digits printed was left out from the calculation. The proposed fix is solving that issue.

### CODE REVIEW

**Comment by jaymin1328** [comment]
@rafagafe please merge

**Comment by krupa32** [comment]
From the man page of snprintf,
```
The functions snprintf() and vsnprintf() do not write more than size bytes (including the terminating 
null byte ('\0')). If the output was truncated due to this limit, then the return value is  the number
of characters (excluding the terminating null byte) which would have been written to the final
string if enough space had been available. Thus, a return value of size or more means that the
output was truncated.  (See also below under NOTES.)
```

Therefore, the return value of snprintf must not be directly used. Rather, if the return is more 
than remLen, then remLen must be subtracted (or can also be set to 0).

**Comment by jaymin1328** [comment]
@krupa32 Thanks for pointing out this detail. See the updated code here in this commit 

https://github.com/rafagafe/json-maker/pull/10/commits/4abb6a332f69a03c3c9d6ee2696ef88efc3e1efa

**Comment by krupa32** [comment]
I did some more testing, and found one more issue.
json-maker does not account for null-termination in remLen, whereas snprintf accounts for null-termination also.
So there is an off-by-one error in this case.
I found this to be the final working solution.

```
321 #define json_num( funcname, type, fmt )                         \
322 char* funcname( char* dest, char const* name, type value, size_t* remLen  ) {    \
323     int len;                                                            \
324     dest = primitivename( dest, name, remLen );                         \
325     len = snprintf( dest, *remLen+1, fmt, value );                      \
326     if (len >= *remLen+1)                                               \
327         len = *remLen;                                                  \
328     *remLen -= len;                                                     \
329     dest += len;                                                        \
330     dest = chtoa( dest, ',', remLen );                                  \
331     return dest;                                                \
332 }
```

**Comment by jaymin1328** [comment]
Done @krupa32 
Please find here 

https://github.com/jaymin1328/json-maker/commit/c4f1cd8da69a9109b248e90a5651b370a41d1e9a

**Comment by krupa32** [comment]
I think there is one more change. The snprintf must be passed `*remLen+1` instead of `*remLen`. The reason is as follows.

The json-maker functions assume remLen to be the available size of chars to be printed WITHOUT the null. However, snprintf assumes the size that is passed includes space for null. Therefore, if you pass `*remLen` to snprintf, it will print only `*remLen-1` chars. However, we want snprintf to print `*remLen` chars as that is the expectation of the json-maker functions. So we need to pass `*remLen+1` to snprintf, so that it can print `*remLen` chars. And whatever we pass to snprintf is what is checked in the next if condition, which is already correct and requires no change. Hope I didn't confuse you too much.

Here are some tests I used to confirm...
```
53 /*
 54  * lets say we generate the json
 55  *   {"hello":12345}
 56  * it takes 15 bytes.
 57  */
 58 static void test_int(void)
 59 {
 60     char buf[32], *p = buf;
 61     size_t rem = 31;
 62 
 63     p = json_objOpen(p, NULL, &rem);
 64     p = json_int(p, "hello", 12345, &rem);
 65     p = json_objClose(p, &rem);
 66     p = json_end(p, &rem);
 67 
 68     CU_ASSERT(rem == 16);
 69     CU_ASSERT_STRING_EQUAL(buf, "{\"hello\":12345}");
 70 
 71     /* insufficient buffer. should only generate
 72      *   {"hello":123
 73      */
 74     rem = 12;
 75     p = buf;
 76     p = json_objOpen(p, NULL, &rem);
 77     p = json_int(p, "hello", 12345, &rem);
 78     p = json_objClose(p, &rem);
 79     p = json_end(p, &rem);
 80 
 81     CU_ASSERT(rem == 0);
 82     CU_ASSERT_STRING_EQUAL(buf, "{\"hello\":123");
 83 }
```

**Comment by jaymin1328** [comment]
@krupa32  in that case you write one more character outside the buffer, in a normal case, it wouldn't matter but when you are at the edge of the buffer, you may write the last character outside of that buffer and that is not good. So sending +1 is a bad idea.

**Comment by krupa32** [comment]
I agree sending +1 is a bad idea. But note that all json-maker functions do that. That is, all json-maker functions assume remLen is number of available chars, and do not take into account the last null-termination. In fact, when we use json-maker in our projects and pass a buf, we intentionally pass len(buf)-1 as remLen, so that json-maker does not ever write the null-termination beyond the buffer.

**Pull request merged**
